-- Spark SQL extraction queries for PayLive AI Copilot
-- Source: simulated big data live events Parquet dataset
-- This file is generated by src/data_collection/collect_from_bigdata.py

-- ============================================================
-- Query name: events_by_live
-- Purpose: Extract and aggregate events from the big data source.
-- ============================================================
SELECT
            live_id,
            COUNT(*) AS total_events,
            COUNT(DISTINCT customer_id) AS unique_customers,
            SUM(CASE WHEN event_type = 'comment_sent' THEN 1 ELSE 0 END) AS comment_events,
            SUM(CASE WHEN event_type = 'cart_opened' THEN 1 ELSE 0 END) AS cart_opened_events,
            SUM(CASE WHEN event_type = 'payment_clicked' THEN 1 ELSE 0 END) AS payment_clicked_events,
            SUM(CASE WHEN event_type = 'payment_succeeded' THEN 1 ELSE 0 END) AS payment_succeeded_events,
            SUM(CASE WHEN event_type = 'api_error' THEN 1 ELSE 0 END) AS api_error_events
        FROM live_events_bigdata
        GROUP BY live_id
        ORDER BY total_events DESC
;

-- ============================================================
-- Query name: payment_funnel_by_live
-- Purpose: Extract and aggregate events from the big data source.
-- ============================================================
SELECT
            live_id,
            SUM(CASE WHEN event_type = 'cart_opened' THEN 1 ELSE 0 END) AS cart_opened_events,
            SUM(CASE WHEN event_type = 'payment_clicked' THEN 1 ELSE 0 END) AS payment_clicked_events,
            SUM(CASE WHEN event_type = 'payment_succeeded' THEN 1 ELSE 0 END) AS payment_succeeded_events,
            CASE
                WHEN SUM(CASE WHEN event_type = 'cart_opened' THEN 1 ELSE 0 END) = 0
                THEN 0
                ELSE ROUND(
                    SUM(CASE WHEN event_type = 'payment_succeeded' THEN 1 ELSE 0 END)
                    / SUM(CASE WHEN event_type = 'cart_opened' THEN 1 ELSE 0 END),
                    4
                )
            END AS payment_success_ratio
        FROM live_events_bigdata
        GROUP BY live_id
        ORDER BY payment_success_ratio DESC
;

-- ============================================================
-- Query name: api_errors_by_live
-- Purpose: Extract and aggregate events from the big data source.
-- ============================================================
SELECT
            live_id,
            source_system,
            COUNT(*) AS api_error_count
        FROM live_events_bigdata
        WHERE event_type = 'api_error'
        GROUP BY live_id, source_system
        ORDER BY api_error_count DESC
;

-- ============================================================
-- Query name: hourly_activity
-- Purpose: Extract and aggregate events from the big data source.
-- ============================================================
SELECT
            event_date,
            event_hour,
            event_type,
            COUNT(*) AS event_count
        FROM live_events_bigdata
        GROUP BY event_date, event_hour, event_type
        ORDER BY event_date, event_hour, event_count DESC
;

-- ============================================================
-- Query name: invalid_events_extract
-- Purpose: Extract and aggregate events from the big data source.
-- ============================================================
SELECT
            event_id,
            source_event_id,
            live_id,
            customer_id,
            event_type,
            event_timestamp,
            event_date,
            event_hour,
            event_value,
            source_system,
            simulation_copy_index
        FROM live_events_bigdata
        WHERE
            live_id IS NULL
            OR TRIM(live_id) = ''
            OR event_timestamp IS NULL
            OR TRIM(event_timestamp) = ''
            OR parsed_event_timestamp IS NULL
            OR event_type NOT IN (
                'comment_sent',
                'cart_opened',
                'payment_clicked',
                'payment_succeeded',
                'api_error',
                'product_viewed'
            )
        ORDER BY event_id
;
