-- SQL extraction queries for PayLive AI Copilot
-- Source: simulated legacy SQLite database
-- This file is generated by src/data_collection/collect_from_database.py

-- ============================================================
-- Query name: legacy_sellers
-- Purpose: Extract data from the simulated legacy SQL database.
-- ============================================================
SELECT
            seller_id,
            shop_name,
            owner_first_name,
            owner_last_name,
            email,
            country,
            main_platform,
            created_at,
            seller_status
        FROM legacy_sellers;
;

-- ============================================================
-- Query name: legacy_live_sessions
-- Purpose: Extract data from the simulated legacy SQL database.
-- ============================================================
SELECT
            live_id,
            seller_id,
            platform,
            live_title,
            actual_start_at,
            ended_at,
            live_status,
            peak_viewers,
            currency
        FROM legacy_live_sessions;
;

-- ============================================================
-- Query name: paid_orders_with_payments
-- Purpose: Extract data from the simulated legacy SQL database.
-- ============================================================
SELECT
            o.order_id,
            o.cart_id,
            o.customer_id,
            o.seller_id,
            s.shop_name,
            c.live_id,
            l.platform AS live_platform,
            o.order_status,
            CAST(NULLIF(o.order_amount, '') AS REAL) AS order_amount,
            o.currency AS order_currency,
            p.payment_id,
            p.payment_provider,
            p.payment_status,
            CAST(NULLIF(p.payment_amount, '') AS REAL) AS payment_amount,
            p.currency AS payment_currency,
            p.payment_method,
            p.paid_at,
            p.transaction_reference
        FROM legacy_orders AS o
        LEFT JOIN legacy_payments AS p
            ON o.order_id = p.order_id
        LEFT JOIN legacy_carts AS c
            ON o.cart_id = c.cart_id
        LEFT JOIN legacy_live_sessions AS l
            ON c.live_id = l.live_id
        LEFT JOIN legacy_sellers AS s
            ON o.seller_id = s.seller_id
        WHERE p.payment_status IN ('succeeded', 'success', 'ok');
;

-- ============================================================
-- Query name: revenue_by_live
-- Purpose: Extract data from the simulated legacy SQL database.
-- ============================================================
SELECT
            c.live_id,
            l.seller_id,
            s.shop_name,
            l.platform AS live_platform,
            COUNT(DISTINCT o.order_id) AS total_orders,
            COUNT(DISTINCT p.payment_id) AS total_payments,
            COUNT(
                DISTINCT CASE
                    WHEN p.payment_status IN ('succeeded', 'success', 'ok')
                    THEN p.payment_id
                END
            ) AS successful_payments,
            ROUND(
                SUM(
                    CASE
                        WHEN p.payment_status IN ('succeeded', 'success', 'ok')
                        THEN CAST(NULLIF(p.payment_amount, '') AS REAL)
                        ELSE 0
                    END
                ),
                2
            ) AS gross_revenue
        FROM legacy_orders AS o
        LEFT JOIN legacy_payments AS p
            ON o.order_id = p.order_id
        LEFT JOIN legacy_carts AS c
            ON o.cart_id = c.cart_id
        LEFT JOIN legacy_live_sessions AS l
            ON c.live_id = l.live_id
        LEFT JOIN legacy_sellers AS s
            ON l.seller_id = s.seller_id
        GROUP BY
            c.live_id,
            l.seller_id,
            s.shop_name,
            l.platform;
;

-- ============================================================
-- Query name: incomplete_orders
-- Purpose: Extract data from the simulated legacy SQL database.
-- ============================================================
SELECT
            o.order_id,
            o.cart_id,
            o.customer_id,
            o.seller_id,
            o.order_status,
            o.order_amount,
            o.currency,
            o.created_at,
            p.payment_id,
            p.payment_status,
            p.payment_amount,
            CASE
                WHEN o.cart_id IS NULL OR TRIM(o.cart_id) = ''
                    THEN 'missing_cart_id'
                WHEN o.customer_id IS NULL OR TRIM(o.customer_id) = ''
                    THEN 'missing_customer_id'
                WHEN o.seller_id IS NULL OR TRIM(o.seller_id) = ''
                    THEN 'missing_seller_id'
                WHEN p.payment_id IS NULL
                    THEN 'missing_payment'
                WHEN CAST(NULLIF(o.order_amount, '') AS REAL) < 0
                    THEN 'negative_order_amount'
                ELSE 'other_issue'
            END AS issue_reason
        FROM legacy_orders AS o
        LEFT JOIN legacy_payments AS p
            ON o.order_id = p.order_id
        WHERE
            o.cart_id IS NULL
            OR TRIM(o.cart_id) = ''
            OR o.customer_id IS NULL
            OR TRIM(o.customer_id) = ''
            OR o.seller_id IS NULL
            OR TRIM(o.seller_id) = ''
            OR p.payment_id IS NULL
            OR CAST(NULLIF(o.order_amount, '') AS REAL) < 0;
;
